### ISSUE TITLE
Pebble fails to start some services on bare-based rock images

### ISSUE THREAD

**Issue by claudiubelu** [canonical/pebble#473] opened 2024-08-05 12:56 UTC
Pebble has an issue with starting some services, if the rock is ``bare``-based, failing with the following error:

```
[pebble] Change 1 task (Start service "envoy") failed: cannot start
service: fork/exec /bin/envoy: no such file or directory
```

This issue has been seen to occur in: [1].

The executable exists in the right place, and overriding the entrypoint and running the binary manually works fine.

Adding the ``base-files`` ``stage-packages`` solves this issue. This has been a workaround in a few cases [2][3].

[1] ghcr.io/canonical/envoy:26bea08ef768fae7411a3a71d20724c53e3092ec63203a9f0bd197a620a8bba6-amd64
[2] https://github.com/canonical/envoy-rock/pull/9
[3] https://github.com/canonical/velero-rocks/blob/e212bfcb40993798763f2cb6ca86074c46e1244c/velero/1.13.2/rockcraft.yaml#L23

**Comment by benhoyt** [comment] 2024-08-06 03:05
Do you know what's in `base-files` that it's adding to the image? Can you think of a good way to diagnose this further? For example, can we run the Rock with a shell in it, and see what's going on? Does setting `PEBBLE_DEBUG=1` show anything? (This will turn on additional Pebble logging.)

**Comment by jnsgruk** [comment] 2024-08-06 07:09
Sounds like `envoy` is trying to itself fork, but what it's trying to fork to doesn't exist without `base-files`, or is trying to dynamically link a library that isn't there? Can you run `strace envoy` and/or `ldd envoy`? Perhaps that will give you a hint?

**Comment by shipperizer** [comment] 2024-08-23 15:54
we have a similar situation where pebble doesn't allow to replan or start the service

```
2024-08-23T15:15:39.767Z [pebble] Service "admin-ui" starting: /usr/bin/identity-platform-admin-ui serve
2024-08-23T15:15:39.838Z [admin-ui] panic: issues with environment sourcing: required key KRATOS_PUBLIC_URL missing value
2024-08-23T15:15:39.838Z [admin-ui] 
2024-08-23T15:15:39.838Z [admin-ui] goroutine 1 [running]:
2024-08-23T15:15:39.838Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.serve()
2024-08-23T15:15:39.838Z [admin-ui] 	/root/parts/go-build/build/cmd/serve.go:62 +0x16f7
2024-08-23T15:15:39.838Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.glob..func4(0xc0009b6600?, {0x1d0215d?, 0x4?, 0x1d02161?})
2024-08-23T15:15:39.838Z [admin-ui] 	/root/parts/go-build/build/cmd/serve.go:49 +0xf
2024-08-23T15:15:39.838Z [admin-ui] github.com/spf13/cobra.(*Command).execute(0x30d1ca0, {0x311dbc0, 0x0, 0x0})
2024-08-23T15:15:39.838Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
2024-08-23T15:15:39.838Z [admin-ui] github.com/spf13/cobra.(*Command).ExecuteC(0x30d19c0)
2024-08-23T15:15:39.838Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
2024-08-23T15:15:39.838Z [admin-ui] github.com/spf13/cobra.(*Command).Execute(...)
2024-08-23T15:15:39.838Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
2024-08-23T15:15:39.838Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.Execute()
2024-08-23T15:15:39.838Z [admin-ui] 	/root/parts/go-build/build/cmd/root.go:22 +0x1a
2024-08-23T15:15:39.838Z [admin-ui] main.main()
2024-08-23T15:15:39.838Z [admin-ui] 	/root/parts/go-build/build/main.go:9 +0xf
2024-08-23T15:15:47.208Z [pebble] GET /v1/notices?timeout=30s 30.001389224s 200
2024-08-23T15:16:01.073Z [pebble] GET /v1/services?names= 180.796µs 200
2024-08-23T15:16:04.919Z [pebble] GET /v1/services?names=help 264.178µs 200
2024-08-23T15:16:17.211Z [pebble] GET /v1/notices?timeout=30s 30.001733471s 200
2024-08-23T15:16:43.139Z [pebble] Cannot look up user 0: open /etc/passwd: no such file or directory
2024-08-23T15:16:43.152Z [pebble] POST /v1/exec 13.603486ms 202
2024-08-23T15:16:43.171Z [pebble] GET /v1/tasks/16/websocket/control 16.621341ms 200
2024-08-23T15:16:43.173Z [pebble] GET /v1/tasks/16/websocket/stdio 216.749µs 200
2024-08-23T15:16:43.175Z [pebble] GET /v1/tasks/16/websocket/stderr 190.601µs 200
2024-08-23T15:16:43.264Z [pebble] GET /v1/changes/16/wait?timeout=4.000s 84.665485ms 200
2024-08-23T15:16:47.213Z [pebble] GET /v1/notices?timeout=30s 30.001469178s 200
2024-08-23T15:17:17.215Z [pebble] GET /v1/notices?timeout=30s 30.000978526s 200
2024-08-23T15:17:47.217Z [pebble] GET /v1/notices?timeout=30s 30.001260616s 200
2024-08-23T15:18:17.219Z [pebble] GET /v1/notices?timeout=30s 30.001437939s 200
2024-08-23T15:18:46.005Z [pebble] POST /v1/services 9.34978ms 202
2024-08-23T15:18:46.014Z [pebble] Service "admin-ui" starting: /usr/bin/identity-platform-admin-ui serve
2024-08-23T15:18:46.088Z [admin-ui] panic: issues with environment sourcing: required key KRATOS_PUBLIC_URL missing value
2024-08-23T15:18:46.088Z [admin-ui] 
2024-08-23T15:18:46.088Z [admin-ui] goroutine 1 [running]:
2024-08-23T15:18:46.088Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.serve()
2024-08-23T15:18:46.088Z [admin-ui] 	/root/parts/go-build/build/cmd/serve.go:62 +0x16f7
2024-08-23T15:18:46.088Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.glob..func4(0xc000a5a600?, {0x1d0215d?, 0x4?, 0x1d02161?})
2024-08-23T15:18:46.088Z [admin-ui] 	/root/parts/go-build/build/cmd/serve.go:49 +0xf
2024-08-23T15:18:46.088Z [admin-ui] github.com/spf13/cobra.(*Command).execute(0x30d1ca0, {0x311dbc0, 0x0, 0x0})
2024-08-23T15:18:46.088Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
2024-08-23T15:18:46.088Z [admin-ui] github.com/spf13/cobra.(*Command).ExecuteC(0x30d19c0)
2024-08-23T15:18:46.088Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
2024-08-23T15:18:46.088Z [admin-ui] github.com/spf13/cobra.(*Command).Execute(...)
2024-08-23T15:18:46.088Z [admin-ui] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
2024-08-23T15:18:46.088Z [admin-ui] github.com/canonical/identity-platform-admin-ui/cmd.Execute()
2024-08-23T15:18:46.088Z [admin-ui] 	/root/parts/go-build/build/cmd/root.go:22 +0x1a
2024-08-23T15:18:46.088Z [admin-ui] main.main()
2024-08-23T15:18:46.088Z [admin-ui] 	/root/parts/go-build/build/main.go:9 +0xf
2024-08-23T15:18:47.220Z [pebble] GET /v1/notices?timeout=30s 30.000938784s 200
2024-08-23T15:19:17.223Z [pebble] GET /v1/notices?timeout=30s 30.001806474s 200

```

issue seems to be related to `[pebble] Cannot look up user 0: open /etc/passwd: no such file or directory` as I'm able to jump in the charm and via pebble cli I can execute the service directly via the binary 

version of pebble is 1.7.2

**Comment by benhoyt** [comment] 2024-08-26 04:58
@shipperizer That looks like a different issue: the service you're running looks like it requires `KRATOS_PUBLIC_URL` to be set, but it's not. Do you need to specify it in your environment?

The logged "Cannot look up user 0: open /etc/passwd: no such file or directory" message is because `HOME` or `USER` are not set, so Pebble tries to look up the username by UID (0/root in this case). But the container it's running on doesn't have a userid-uid mapping (the `/etc/passwd` file), so it logs that message. It's not an error; it just means that `HOME` and `USER` won't be set (but they're likely not needed). Arguably it shouldn't even be logged.

**Comment by shipperizer** [comment] 2024-08-26 05:47
> @shipperizer That looks like a different issue: the service you're running looks like it requires `KRATOS_PUBLIC_URL` to be set, but it's not. Do you need to specify it in your environment?
> 
> The logged "Cannot look up user 0: open /etc/passwd: no such file or directory" message is because `HOME` or `USER` are not set, so Pebble tries to look up the username by UID (0/root in this case). But the container it's running on doesn't have a userid-uid mapping (the `/etc/passwd` file), so it logs that message. It's not an error; it just means that `HOME` and `USER` won't be set (but they're likely not needed). Arguably it shouldn't even be logged.

we are looking into what the charm is doing wrong, environment is passed to pebble in the code and KRATOS public variables are there https://github.com/canonical/identity-platform-admin-ui-operator/blob/main/src/services.py#L113

**Comment by benhoyt** [comment] 2024-09-30 01:20
@IronCore864 Will take a closer look at this and try to repro.

**Comment by IronCore864** [comment] 2024-10-15 14:45
I have been trying to reproduce the issue by first building the rock image, but I met [this issue](https://github.com/envoyproxy/envoy/issues/36563) and could not have a successful build. I will try it again later.

**Comment by claudiubelu** [comment] 2024-10-15 19:38
> I have been trying to reproduce the issue by first building the rock image, but I met [this issue](https://github.com/envoyproxy/envoy/issues/36563) and could not have a successful build. I will try it again later.

Envoy is a bulky binary to build, it will take you quite a while to just build it.

You can try it with the Velero rock instead, As mentioned in the issue, it happens there as well, and it is somehow resolved by having ``base-files`` ``stage-packages``.

**Comment by dimaqq** [comment] 2024-10-16 06:12
Quick note from today's stand-up:

Having `base-files` is probably correct anyway.

The reason for that is https://wiki.debian.org/UsrMerge and base-files includes the customary symlinks.

This is based on the assumption that the reason for exec failure is misatch between compiled library path / LD_LIBRARY_PATH and container filesystem layout, that is, let's say Envoy needs `libpcre2-8.so.0`, normal Ubuntu has that available as both `/usr/lib/aarch64-linux-gnu/libpcre2-8.so.0.11.2` and `/lib/aarch64-linux-gnu/libpcre2-8.so.0.11.2`, with some symlinks handling the confusion. Raw rock doesn't have the symlinks. This can be fixed in variety of ways, depending on your needs; Arguably, the symlinks are the most understandable way.

@IronCore864 will probably dig a bit more into the specific rocks, because he said he wanted to understand what's really going on, as opposed to an assumption above.

**Comment by IronCore864** [comment] 2024-10-17 04:26
A summary of the progress of reproducing and debugging this issue:

Reproducing with envoy failed because of [this issue](https://github.com/envoyproxy/envoy/issues/36563). There seems to be no easy workaround and we can only wait until it's fixed.

Reproducing with Velero in two ways, local and k8s helm deploy:

Local: rockcraft pack with base-files removed then run a container from the image with the entrypoint overridden to `/velero`. The result is successful wit no `fork/exec` or `no such file or directory` error, can't reproduce.

K8s: run integration tests locally using an image with base-files removed. This will install k8s locally, and then deploy Minio and Velero. The job `velero-upgrade-crds` failed, the container args are:

```yaml
      - args:
        - -c
        - /velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -
        command:
        - /tmp/sh
```

Error: `exec /tmp/sh: no such file or directory`. This is somewhat similar to the issue but not precisely the same, the error is because the `/tmp` folder doesn't exist, even if we tried to add it explicitly in rockcraft with:

```yaml
parts:
  add-tmp:
    plugin: nil
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}/tmp"
```

To sum up, I think it's reasonable to add the base-files package to a bare-based image, but the question remains: what binaries and programs need it and what not? There seems to be no reliable information on this in the rockcraft documentation.

Regarding the envoy error, our deduction is that the binary isn't actually missing (although that's what the error message suggested), but rather, it's some envoy dependency lib that is missing.

The theory is, in base-files, [here](https://git.launchpad.net/ubuntu/+source/base-files/tree/debian/base-files.lintian-overrides#n27) adds a few symlinks, like `/usr/lib` to `/lib`, and `/usr/lib64` to `/lib64`. It's possible that without base-file (without these links), some dependency lib of envoy can't be found, hence the error.

Due to the envoy build failure, we could not reproduce this for now, but it's a reasonable deduction.

Shall we close this issue since it's most likely pebble-related? Or shall we wait till the envoy build is fixed and try again? @benhoyt 

At the same time, I will try to reproduce using a simple hello-world binary with Pebble without overriding the entrypoint.

**Comment by benhoyt** [comment] 2024-10-18 03:00
Yes, I think we should close this issue, as it's pretty clearly not a Pebble issue. Regarding your question:

> the question remains: what binaries and programs need it and what not? There seems to be no reliable information on this in the rockcraft documentation.

Yeah, it's likely this could be better documented in Rockcraft. However, it's probably program-specific, depending on what (or whether) shared libraries are used.

**Closed by benhoyt** 2024-10-18 03:00 UTC
Labels: 24.10

**Comment by claudiubelu** [comment] 2024-10-21 16:26
Hello,

I've spent a bit of time investigating this issue as well, and I'm going to offer some information and tips and tricks for other people that may have experienced something similar.

Regarding the original issue, the ``service fork/exec /bin/envoy`` part may have been a bit of a red herring. At first glance looking like it might have some issues with ``fork`` specifically, but no, it's just the ``exec`` part itself, or more exactly, just executing the binary itself.

I've compared 2 envoy rocks, one with ``base-files`` (ghcr.io/canonical/envoy:1.28.2-ck3), and one without (ghcr.io/canonical/envoy:21e1fc053482c78ee3fbb31c72a94ba60feaa8ef7a9b91d19e03c298feaf669c-amd64). Running the one without ``base-files`` results in these errors:

```
docker run --rm -ti ghcr.io/canonical/envoy:21e1fc053482c78ee3fbb31c72a94ba60feaa8ef7a9b91d19e03c298feaf669c-amd64
2024-10-21T14:44:48.570Z [pebble] Started daemon.
2024-10-21T14:44:48.611Z [pebble] POST /v1/services 23.867215ms 202
2024-10-21T14:44:48.625Z [pebble] Service "envoy" starting: envoy [ -c /etc/envoy/envoy.yaml ]
2024-10-21T14:44:48.626Z [pebble] Change 1 task (Start service "envoy") failed: cannot start service: fork/exec /bin/envoy: no such file or directory
2024-10-21T14:44:48.651Z [pebble] GET /v1/changes/1/wait 39.37006ms 200
2024-10-21T14:44:48.651Z [pebble] Started default services with change 1.

docker run --rm -ti --entrypoint /bin/envoy ghcr.io/canonical/envoy:21e1fc053482c78ee3fbb31c72a94ba60feaa8ef7a9b91d19e03c298feaf669c-amd64
exec /bin/envoy: no such file or directory
```

While the good image does not have this issue:

```
 docker run --rm -ti ghcr.io/canonical/envoy:1.28.2-ck3
2024-10-21T14:45:43.536Z [pebble] Started daemon.
2024-10-21T14:45:43.563Z [pebble] POST /v1/services 13.221055ms 202
2024-10-21T14:45:43.576Z [pebble] Service "envoy" starting: envoy [ -c /etc/envoy/envoy.yaml ]
2024-10-21T14:45:44.594Z [pebble] GET /v1/changes/1/wait 1.031115374s 200
2024-10-21T14:45:44.595Z [pebble] Started default services with change 1.

docker run --rm -ti --entrypoint /bin/envoy ghcr.io/canonical/envoy:1.28.2-ck3
[2024-10-21 14:45:55.947][1][info][main] [source/server/server.cc:413] initializing epoch 0 (base id=0, hot restart version=11.104)
[2024-10-21 14:45:55.947][1][info][main] [source/server/server.cc:415] statically linked extensions:
[2024-10-21 14:45:55.947][1][info][main] [source/server/server.cc:417]   envoy.retry_priorities: envoy.retry_priorities.previous_priorities
...
```

So, I exported the images and compared what the differences are:

```
# Create a tmp location.
mkdir /tmp/envoy-base-files
cd /tmp/envoy-base-files
docker save -o envoy-base-files.tar ghcr.io/canonical/envoy:1.28.2-ck3

# Unpack the image and all its layers.
tar -xvf *.tar
manifest_digest="$(cat index.json | jq -r '.manifests[0].digest' | cut -d: -f2)"
blobs="$(cat blobs/sha256/$manifest_digest | jq -r '.layers[] | .digest' | tac | cut -d: -f2)"
for blob in $blobs; do tar -xvf "blobs/sha256/$blob"; done

# chroot into this directory and exec what pebble is supposed to run in the first place.
sudo chroot . /bin/envoy


# Create a tmp location.
mkdir /tmp/envoy-no-base-files
cd /tmp/envoy-no-base-files
docker save -o envoy.tar ghcr.io/canonical/envoy:21e1fc053482c78ee3fbb31c72a94ba60feaa8ef7a9b91d19e03c298feaf669c-amd64

# Unpack the image and all its layers.
tar -xvf *.tar
manifest_digest="$(cat index.json | jq -r '.manifests[0].digest' | cut -d: -f2)"
blobs="$(cat blobs/sha256/$manifest_digest | jq -r '.layers[] | .digest' | tac | cut -d: -f2)"
for blob in $blobs; do tar -xvf "blobs/sha256/$blob"; done

# chroot into this directory and exec what pebble is supposed to run in the first place. It should fail.
sudo chroot . /bin/envoy
```

The above script is ``chroot``-ing into what a container would essentially have a filesystem. In the first case, the ``envoy`` binary is starting as expected, while the second one is getting the error: ``chroot: failed to run command ‘/bin/envoy’: No such file or directory``. Looking at the contents, ``lib`` and ``lib64`` stand out (added by ``base-files`` ``stage-package``). Copying them over will make ``envoy`` start:

```
cp -r /tmp/envoy-base-files/lib /tmp/envoy-no-base-files/
cp -r /tmp/envoy-base-files/lib64 /tmp/envoy-no-base-files/

# Envoy should now start.
sudo chroot /tmp/envoy-no-base-files/ /bin/envoy
```

So, as an important note, ``base-files`` ``stage-package`` contains those ``lib`` and ``lib64`` folders, which are necessary for binaries which are **not statically linked**.

I've tried this with another rock image, which contained a go binary, and it had the same issue as the envoy rock. Same thing happened there. However, it seems that the ``base-files`` ``stage-package`` is not necessary if you set the ``CGO_ENABLED=0`` flag when building the binary (see here: https://forum.golangbridge.org/t/what-is-the-difference-between-a-binary-built-with-cgoenabled-0-from-the-default-mode/30531). So, you can have a part like this in ``rockcraft.yaml``:

```
  build-binary:
    plugin: go
    source: .
    build-snaps:
      - go/1.23/stable
    build-environment:
      - GOOS: linux
      - GOARCH: $CRAFT_ARCH_BUILD_FOR
      - CGO_ENABLED: 0
    go-generate:
      - ./cmd
```

Not needing the ``base-files`` ``stage-package`` results in an even smaller rock size:

```
ls -liah *.rock
5681574 -rw-r--r-- 1 ubuntu ubuntu 19M Oct 21 08:44 rocky_0.0.1_amd64-bare-with-base-files.rock
5681555 -rw-r--r-- 1 ubuntu ubuntu 13M Oct 21 08:40 rocky_0.0.1_amd64-bare-cgo-no-base-files.rock
5680249 -rw-r--r-- 1 ubuntu ubuntu 41M Oct 21 08:48 rocky_0.0.1_amd64-ubuntu2204-base.rock
```

Keep in mind that the ``base-files`` ``stage-package`` contains a few other things as well: https://git.launchpad.net/ubuntu/+source/base-files/tree/debian/base-files.lintian-overrides#n27 (as mentioned by @IronCore864). So, as a quick tip for anyone stumbling onto this issue: if you're going with a bare-based image (of any kind, not just rocks), you should probably statically link your binary, and make sure it has all the folders it expects to exist. Note that ``rockcraft`` has "slices" of the ``base-files`` package, allowing you install exactly what you need. For example, instead of ``base-files`` you could use ``base-files_lib``. Regarding those "slices", I didn't find any official documentation with public slices, I've only found this: https://github.com/canonical/chisel-releases/tree/ubuntu-22.04/slices. It would be great if this list would be easier to find.

> Do you know what's in `base-files` that it's adding to the image? Can you think of a good way to diagnose this further? For example, can we run the Rock with a shell in it, and see what's going on? Does setting `PEBBLE_DEBUG=1` show anything? (This will turn on additional Pebble logging.)

``chroot``-ing helped to a degree for some images, to at least see whether or not the binary can actually start (which is sufficient), though for binaries that has to interact a lot with a filesystem / system, it'll error out eventually. This may be useful for someone:

```
# Create a tmp location and copy the rock there.
mkdir /tmp/rocky
cp *.rock /tmp/rocky/
cd /tmp/rocky

# Unpack the rock and all its layers.
tar -xvf *.rock
manifest_digest="$(cat index.json | jq -r '.manifests[0].digest' | cut -d: -f2)"
blobs="$(cat blobs/sha256/$manifest_digest | jq -r '.layers[] | .digest' | tac | cut -d: -f2)"
for blob in $blobs; do tar -xvf "blobs/sha256/$blob"; done

# chroot into this directory and exec what pebble is supposed to run in the first place.
sudo chroot . /mutating-pebble-webhook
```

This is a bit of a random thought, but it might be useful if ``rockcraft`` would have some sort of validation stage for the rock, in which it could verify that the binaries it contains can actually start.


> A summary of the progress of reproducing and debugging this issue:
> 
> Reproducing with envoy failed because of [this issue](https://github.com/envoyproxy/envoy/issues/36563). There seems to be no easy workaround and we can only wait until it's fixed.
> 
> Reproducing with Velero in two ways, local and k8s helm deploy:
> 
> Local: rockcraft pack with base-files removed then run a container from the image with the entrypoint overridden to `/velero`. The result is successful wit no `fork/exec` or `no such file or directory` error, can't reproduce.
> 
> K8s: run integration tests locally using an image with base-files removed. This will install k8s locally, and then deploy Minio and Velero. The job `velero-upgrade-crds` failed, the container args are:
> 
> ```yaml
>       - args:
>         - -c
>         - /velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -
>         command:
>         - /tmp/sh
> ```
> 
> Error: `exec /tmp/sh: no such file or directory`. This is somewhat similar to the issue but not precisely the same, the error is because the `/tmp` folder doesn't exist, even if we tried to add it explicitly in rockcraft with:
> 
> ```yaml
> parts:
>   add-tmp:
>     plugin: nil
>     override-build: |
>       mkdir -p "${CRAFT_PART_INSTALL}/tmp"
> ```
> 
> To sum up, I think it's reasonable to add the base-files package to a bare-based image, but the question remains: what binaries and programs need it and what not? There seems to be no reliable information on this in the rockcraft documentation.


Right. So, @IronCore864 and I have looked in this (thanks btw!), and ineed, we have seen that `exec /tmp/sh: no such file or directory`, which was extremely confusing. I say this because the ``/tmp`` folder definitely already existed, as it was an ``emptyDir`` volume, and ``tmp/sh`` was copied over from an ``initContainer`` (https://github.com/vmware-tanzu/helm-charts/blob/47b2f729b9ebe38508ecc046560da01922546df6/charts/velero/templates/upgrade-crds/upgrade-crds.yaml#L56-L67). I should also mention that ``/velero`` itself is a golang binary built with ``CGO_ENABLED=0`` as mentioned above, so the ``velero`` binary itself actually works (I've unpacked the rock with the script above):

```
sudo chroot . /velero install --crds-only --dry-run -o yaml | head -n 5
apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
```

However, the actual command executed in the `velero-upgrade-crds` job above is: ``/tmp/sh -c "/velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -"``. So, let's try this instead:

```
mkdir tmp
cp "$(which sh)" tmp/

sudo chroot . /tmp/sh -c "/velero install --crds-only --dry-run -o yaml"

chroot: failed to run command ‘/tmp/sh’: No such file or directory
```

So, that's why we saw the ``exec /tmp/sh: no such file or directory`` at that time. ``sh`` isn't statically compiled, which is why we got this error. I didn't think about this at the time. But, if we copy over the ``lib`` and ``lib64`` folders as before, it should work:

```
# Create a tmp location.
mkdir /tmp/velero
cd /tmp/velero
docker pull ghcr.io/canonical/velero:1.13.2-ck2
docker save -o velero.tar ghcr.io/canonical/velero:1.13.2-ck2

# Unpack the image and all its layers.
tar -xvf *.tar
manifest_digest="$(cat index.json | jq -r '.manifests[0].digest' | cut -d: -f2)"
blobs="$(cat blobs/sha256/$manifest_digest | jq -r '.layers[] | .digest' | tac | cut -d: -f2)"
for blob in $blobs; do tar -xvf "blobs/sha256/$blob"; done

# copy lib and lib64
cp -r lib /tmp/rocky/
cp -r lib64 /tmp/rocky/

# Create a tmp location.
mkdir /tmp/kubectl
cd /tmp/kubectl
docker pull ghcr.io/canonical/kubectl:1.30.2-ck5docker save -o velero.tar ghcr.io/canonical/velero:1.13.2-ck2

# Unpack the image and all its layers.
tar -xvf *.tar
manifest_digest="$(cat index.json | jq -r '.manifests[0].digest' | cut -d: -f2)"
blobs="$(cat blobs/sha256/$manifest_digest | jq -r '.layers[] | .digest' | tac | cut -d: -f2)"
for blob in $blobs; do tar -xvf "blobs/sha256/$blob"; done

# copy /bin/sh, the same way the init container would do.
cp bin/sh /tmp/rocky/tmp/

sudo chroot /tmp/rocky/ /tmp/sh -c "/velero install --crds-only --dry-run -o yaml" | head -n 5

 -n 5
apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
```

So, yeah. ``sh`` was missing ``lib`` and ``lib64``.


> Shall we close this issue since it's most likely pebble-related? Or shall we wait till the envoy build is fixed and try again? @benhoyt
> 

FWIW, the envoy rock build was fixed, and there's also an envoy arm64 rock image for you without ``base-files`` and one with ``base-files`` for you to try out if you want. But I think we've researched this issue enough and figured out what was happening, and there isn't anything else needed to know.

Thanks folks for your help in investigating this issue!

**Comment by tonyandrewmeyer** [comment] 2024-10-21 18:57
That's an exceptionally good write-up - thanks so much!

**Comment by benhoyt** [comment] 2024-10-22 09:43
Agreed, thanks for that, @claudiubelu! Would you be interested in posting that write-up as a "debugging journey" or something on our Ubuntu Discourse in the Rocks category? https://discourse.ubuntu.com/c/rocks/117 Might be useful for others who run into the same issue and want to learn more.
