### ISSUE TITLE
Forward signals to child processes

### ISSUE THREAD

**Issue by amouat** [canonical/pebble#6] opened 2021-02-02 16:28 UTC
Assuming pebble runs a PID 1 in a container, it needs to take care of some tasks, most notably forwarding signals to child processes and dealing with zombie & orphan processes. Handling signals is especially key, as this is required to allow processes to shutdown cleanly e.g. databases to finish writes and log, web apps to handle final requests. At the moment, signal forwarding doesn't seem to be happening by default at least.

To test this I used the following Dockerfile:

```
FROM debian:latest

COPY pebble /pebble
COPY test.sh /test.sh
RUN mkdir --parents /.pebble/layers
COPY 01.yaml /.pebble/layers/
ENV PEBBLE /.pebble

CMD ["/pebble", "run"]
```

With the pebble config:
```
summary: Test Layer

services:

    srv1:
        override: replace
        summary: Service summary
        command: /test.sh
        default: start
```

And test.sh:

```
#!/bin/bash

function shutdown()
{
    echo "Graceful shutdown" >> /log
    exit
}

trap shutdown SIGTERM

echo "Started" >> /log
while true
do
    echo Sleeping >> /log
    sleep 10
done
```

Build this image and run it using Docker:

```
$ docker build -t test .
...
$ docker run -d --name test testdocker run 
```

Now run `docker stop` which will send a SIGTERM to the container and then look at the logfile:

```
$ docker stop test
test
$ docker cp test:/log ./log
$ cat log
Started
Sleeping
Sleeping
```

Note that "Graceful shutdown" does not appear, indicating that the signal is not being forwarded to the child process. If we test the same script with [tini](https://github.com/krallin/tini/) we can observe the correct behaviour: 

```
$ cat Dockerfile.tini
FROM debian:latest

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
COPY test.sh /test.sh

CMD ["/tini", "--", "/test.sh"]

$ docker build -f Dockerfile.tini -t test-tini .
...
$ docker rm test-tini                     
test-tini
$ docker run -d --name test-tini test-tini 
853db290cfeeb797d21203ccfa07221b7e2f6ef34b0f755a6e97bd4471ad8d16
$ docker stop test-tini
test-tini

$ docker cp test-tini:/log ./log
$ cat log
Started
Sleeping
Graceful shutdown
```

In the future, signal handling could be a great place for pebble to innovate, for example adding hooks to allow extra processing on signals - I can imagine writing extra messages to logs or sending shutdown warnings to dependents.

**Comment by marceloneppel** [comment] 2022-01-13 20:54
Hi team! We are currently developing a charm for Postgres on Kubernetes using a tool called [Patroni](https://github.com/zalando/patroni) to do the replication of the data between the Postgres instances.

The current replication implementation (in draft) can be checked [here](https://github.com/marceloneppel/postgresql-k8s-operator/tree/replication). It can be used with this [docker image](https://github.com/canonical/postgresql-patroni-container/tree/docker-image). We also tested with the [example image](https://github.com/zalando/patroni/blob/master/kubernetes/Dockerfile) from Patroni’s repository, changing the charm code to use the `postgres` user in the pebble layer.

The charm correctly deploys and handles the replication when, for example, we deploy 3 units. We can connect in the leader instance and do some writes to see the data being replicated to the other instances.

The problem happens when we remove the leader unit (the one which accepts both reads and writes) and a failover process / new leader election is triggered (don’t confuse it with juju/charm leadership).

At this moment, another replica is correctly elected as a leader, but the other ones keep stuck in a process of restarting Postgres. The problem is that Patroni waits for Postgres process to be restarted in the replica units that were not elected as leader in this failover process (firstly by checking that the process was completely stopped) when changing the leader (after deleting the unit leader or crashing the patroni/postgres process, for example), but the postgres process becomes in a defunct/zombie state (which prevents the restart to be completed (because the zombie process it’s being considered as in not stopped yet) and the parent of the zombie process seems to be the process with pid 1 (/charm/bin/pebble run --create-dirs --hold --verbose - in the logs later). This restart process is a logic of Patroni, in order to resync the replicas with the new leader.

We have the logs of an example deployment with 3 units, where the first unit was the leader. Then, we triggered a failover by killing the Patroni process with `kill -9`in this unit. These are the logs:

[Juju logs](https://paste.ubuntu.com/p/7XKGRxJmzm/)

[Unit 0 logs](https://paste.ubuntu.com/p/KZzQ24XPWB/) (first leader; unit in which I killed the patroni process to do the failover)

[Unit 1 logs](https://paste.ubuntu.com/p/sBrYm4X8sD/) (which was kept as a replica after the failover and has the problem - zombie process - the message "Lock owner: postgresql-k8s-2; I am postgresql-k8s-1" is Patroni waiting for the postgres process to stop)

[Unit 2 logs](https://paste.ubuntu.com/p/B7YrcXMHdP/) (which became the leader after the failover - it's ok)

Here are the processes in the second unit (the one that was kept as a replica in this group and that got the zombie process). Looks like pebble is the parent, even though Patroni has started Postgres.

```
root@postgresql-k8s-2:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0 711432  8740 ?        Ssl  11:44   0:00 /charm/bin/pebble run --create-dirs --hold --verbose
postgres      14  0.0  0.0  19656  3248 ?        S    11:44   0:00 /bin/bash /entrypoint.sh
postgres      16  0.3  0.2 934760 36516 ?        Sl   11:44   0:01 /usr/bin/python3 /usr/local/bin/patroni /home/postgres/patroni.yml
postgres      33  0.0  0.0      0     0 ?        Z    11:44   0:00 [postgres] <defunct>
root          76  0.0  0.0  19880  3704 pts/0    Ss   11:48   0:00 /bin/bash
root          90  0.0  0.0  38312  3312 pts/0    R+   11:49   0:00 ps aux
root@postgresql-k8s-2:/# ps -o ppid= -p 33
      1
```

We can have the correct failover if we deploy just part of the resources (statefulset, secrets and endpoint) of the [manifest](https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml) from Patroni repository. We are not sure, but maybe the difference can be related to some signal not being redirected by Pebble to the Patroni or Postgres processes.

Versions that were used in these tests:
Juju 2.9.22
Microk8s 1.22.4

**Comment by jnsgruk** [comment] 2022-01-14 10:56
So to be clear: the thing that kills the Postgres process here is Patroni itself, which it does automatically when it detects a new leader has been elected? We're not at any point kicking Patroni over from the charm code?

**Comment by marceloneppel** [comment] 2022-01-14 11:05
> So to be clear: the thing that kills the Postgres process here is Patroni itself, which it does automatically when it detects a new leader has been elected? We're not at any point kicking Patroni over from the charm code?

Yes Jon. We are not calling this failover or sending any signal to Patroni through the charm code. Patroni itself sends a stop signal to Postgres when it detects that the something has changed in the instances group (the leader of the replication group has failed).

**Comment by marceloneppel** [comment] 2022-01-14 21:22
Here is an example repository to give some info about the problem that is happening: https://github.com/marceloneppel/patroni-replication-test

**Comment by benhoyt** [comment] 2022-01-18 03:14
@marceloneppel Thanks for the detailed notes and repro repo. A couple of follow-up questions:

> We have the logs of an example deployment with 3 units, where the first unit was the leader. Then, we triggered a failover by killing the Patroni process with `kill -9` in this unit. These are the logs:

It seems to me that if you kill something with `kill -9` (`SIGKILL`) the OS will kill that process instantly and the process won't get a chance to handle the signal in any case. So killing with `SIGKILL` can't forward the signal to child processes, whereas `SIGTERM` can (but Pebble doesn't at the moment). So I guess I'm curious why you're using `kill -9` here?

> Here is an example repository to give some info about the problem that is happening: https://github.com/marceloneppel/patroni-replication-test

This is great, thanks. From looking at the source, it seems you're using `kubectl delete <pod>`, which according to the docs performs graceful shutdown of the pod (and then is forcibly terminated after the grace period). This is in contrast to `kill -9`.

> If I get some time, I'll add some other supervisor process like, for example, supervisord , in order to check if something similar happens and the problem could be in Patroni.

That would be great if you can -- thanks.

On this end I'll also try to create a small reproducer that just uses Pebble and a test program with children, rather than Docker/K8s/Patroni. I just want to narrow it down.

**Comment by benhoyt** [comment] 2022-01-18 03:45
Actually, on my last comment, I guess @amouat has already done that, with his bare Docker + test.sh reproducer. In that case I think I know roughly what I need to do -- just need to make a plan and fix this. I'll see if I can do this (or at least make a start) this week.

**Comment by marceloneppel** [comment] 2022-01-18 14:32
Hi @benhoyt! Thanks for the updates.

About the questions:

> It seems to me that if you kill something with kill -9 (SIGKILL) the OS will kill that process instantly and the process won't get a chance to handle the signal in any case. So killing with SIGKILL can't forward the signal to child processes, whereas SIGTERM can (but Pebble doesn't at the moment). So I guess I'm curious why you're using kill -9 here?

There is no specific reason for using `kill -9`. I just used it to break the node sometimes when I deployed Patroni using the charm and juju and the leader was not the last unit (so I couldn't use `juju remove-unit`) and because there was a different behavior if I deleted the pod with `kubectl delete` (the unit/pod restarted so fast that the same unit became the leader again). The information that you wrote it's important, about the use of SIGTERM instead of SIGKILL. Thanks for that.

> This is great, thanks. From looking at the source, it seems you're using kubectl delete <pod>, which according to the docs performs graceful shutdown of the pod (and then is forcibly terminated after the grace period). This is in contrast to kill -9.

Yes. It's a different approach here. I also saw that the same problem happen if we use `kill -9` in this scenario (the problem happens in other unit; but there may be a signal or other info being sent during the graceful shutdown).

I updated the [repo](https://github.com/marceloneppel/patroni-replication-test) with a test using `supervisord` being used to start patroni. I tried to make it as similar as possible to the test using pebble.

> Actually, on my last comment, I guess @amouat has already done that, with his bare Docker + test.sh reproducer. In that case I think I know roughly what I need to do -- just need to make a plan and fix this. I'll see if I can do this (or at least make a start) this week.

Great! Thanks again for all the support in this issue!

**Comment by benhoyt** [comment] 2022-01-21 04:00
Unfortunately I had other things to work on this week and only started looking into this. Next week I'll mostly be working on health checks, but hopefully this can come after that. My intention is to change the `run` command to accept a `--forward-signals` option, and if set, get notified about all signals, and when it receives them, forward them to all running services.

Alternative configuration options:

1) Is the `--forward-signals` option needed? Maybe we just always forward them. And presumably we should forward to the process group, not just the individual pid.
2) Or does this need to be configurable on a per-service basis in the layer configuration? Either way, we can probably start with it forwarding by default, and add a `signal-forwarding: false` option in the config YAML later if needed.

Thoughts?

**Comment by jnsgruk** [comment] 2022-01-21 07:35
Not sure if I've missed the point here (very possible!) but in Marcelo's case, he's not actually sending a signal to a pebble managed process, it's a pebble managed process killing one of its children that results in the defunct/zombie process. Will the above address such a situation?

**Comment by jnsgruk** [comment] 2022-01-21 07:38
I wonder if this issue has become confused with two separate problems - your solution above sounds like it'll nail the original problem 🙂

**Comment by benhoyt** [comment] 2022-01-25 08:51
As we discussed tonight, the fix in https://github.com/canonical/pebble/pull/99 may fix @marceloneppel's issue, because Pebble is going to be the process reaper. Not quite sure though -- we'll see. I may be able to give @marceloneppel a special branch of Pebble to confirm this, but EOD for me now.

**Comment by benhoyt** [comment] 2022-01-25 23:23
Hey @marceloneppel: we'd like to test the theory that setting Pebble as the child subreaper will fix this. Are you able to build a branch of Juju that has a version of Pebble which sets the child subreaper flag, and test with that? Here's a Juju draft branch/PR with a brief note on how to build Juju: https://github.com/juju/juju/pull/13654 ... let me know if you need any more info.

**Comment by marceloneppel** [comment] 2022-01-26 19:20
> Hey @marceloneppel: we'd like to test the theory that setting Pebble as the child subreaper will fix this. Are you able to build a branch of Juju that has a version of Pebble which sets the child subreaper flag, and test with that? Here's a Juju draft branch/PR with a brief note on how to build Juju: [juju/juju#13654](https://github.com/juju/juju/pull/13654) ... let me know if you need any more info.

Thank you so much for that, @benhoyt! I tried to test by following your instructions on [juju/juju#13654](https://github.com/juju/juju/pull/13654), but I could not deploy the charm using the juju version that I compiled and installed. Maybe I'm missing something.

I compiled and installed juju with `make install` and also built the Docker image for the microk8s operator with `make microk8s-operator-update`. Then I created a controller and a model with `juju bootstrap microk8s micro` and `juju add-model dev`. I also imported my PostgreSQL+Patroni Docker image to microk8s with `docker save patroni | microk8s ctr images import -`. Finally, I built the charm with `charmcraft pack` and deployed it with `juju deploy`. With that, the charm got stuck in the `installing agent` status and juju debug-log shows [this logs](https://paste.ubuntu.com/p/gXrpd8C2ym/). These are the versions of the tools that I'm using:

* go1.17.6 linux/amd64
* GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
* juju compiled version: 2.9.24-ubuntu-amd64
* charmcraft 1.4.0
* lxd 4.0.8
* microk8s 1.23/stable

I also tried to test only pebble in my [sample test repository PR](https://github.com/marceloneppel/patroni-replication-test/pull/4), but seem that the issue still happens.

**Comment by benhoyt** [comment] 2022-01-27 03:11
@marceloneppel Hmm, that's odd about the Juju error. In any case, assuming your sample test repo can reliably reproduce the problem, the fact that it still happens on the test repo on the `set-child-subreaper` branch means that this won't fix it. Thanks for testing.

**Comment by marceloneppel** [comment] 2022-02-07 12:00
Hi @benhoyt! I tried #101 here in my sample test repo and it looks like it solved the zombie process problem. I'll make some more tests and also try to test using this changes from pebble in Juju to confirm.

**Comment by benhoyt** [comment] 2022-06-20 22:26
We addressed the "reaping zombies" issue in https://github.com/canonical/pebble/pull/101 and the signal handling in https://github.com/canonical/pebble/pull/114 (note that we addressed this by handling SIGTERM/SIGQUIT/SIGINT and stopping all services - i.e., sending SIGTERM to each and waiting up to 5s for them to exit).

**Closed by benhoyt** 2022-06-20 22:26 UTC
