### ISSUE TITLE
Service reload command

### ISSUE THREAD

**Issue by dstathis** [canonical/pebble#30] opened 2021-04-26 21:30 UTC
I think it would be very useful to be able to define a service reload command (or maybe some other method like a signal) and be able to reload through pebble. Having to always restart can lower availability.

**Comment by benhoyt** [comment] 2021-05-04 00:59
Thanks @dstathis. This is a dupe of https://github.com/canonical/pebble/issues/16, so closing this is favour of that existing one.

**Closed by benhoyt** 2021-05-04 00:59 UTC
