### ISSUE TITLE
Pebble creates a large number of threads

### ISSUE THREAD

**Issue by jnsgruk** [canonical/pebble#15] opened 2021-03-17 13:32 UTC
In testing @benhoyt's snappass charm, I noticed that `pebble` was creating (and not terminating) an ever growing number of threads.

This can be replicated like so (assuming Juju is bootstrapped on Microk8s)

```bash
$ juju add-model snappass
$ juju deploy snappass-test --resource snappass-image=benhoyt/snappass-test --resource redis-image=redis
# Wait for the app to start - watch in `juju status` output
$ kubectl -n snappass exec -it snappass-test-0 -c snappass -- /bin/bash
$ watch -n1 "cat /proc/1/status | grep Thread"
```

After running the workload for ~1hour there were over 800 threads (albeit sleeping but still present) in each container. The climbing number of threads seems to correlate to calls to the `/v1/system-info` endpoint. I only came to this conclusion by watching the growing number of threads, which seemed to correlate to additions to the container logs as observed with:

```
kubectl logs -n snappass -c snappass snappass-test-0 -f
```

**Comment by jnsgruk** [comment] 2021-03-17 13:40
Confirmed the same occurs with @mthaddon's gunicorn pebble charm.

**Comment by benhoyt** [comment] 2021-03-18 02:00
Yeah, this is pretty concerning. It doesn't seem to be happening when running Pebble on my laptop locally (it goes up to 15 threads and then stops, which seems somewhat reasonable). However, I can reproduce easily in the K8s/Juju context with the `snappass-test` charm. The thread count goes up every 5s (which, like you say, is how often Juju polls `/v1/system-info`). I'll dig in soon.

**Comment by benhoyt** [comment] 2021-03-19 01:10
As @hpidcock discovered, this is due to creating a new `pebble.Client` every time we poll, and keep-alives are enabled, so there's a thread actively waiting on I/O each time. We'll fix shortly (either by closing idle connections or not using keep-alive in the first place).

**Comment by benhoyt** [comment] 2021-03-19 04:10
@hpidcock fixed this in https://github.com/juju/juju/pull/12783 -- will be in the next 2.9 rc of Juju.

**Closed by benhoyt** 2021-03-19 04:10 UTC
