### ISSUE TITLE
The service appears to be running, even the command ends with exit code 1

### ISSUE THREAD

**Issue by r-f-g** [canonical/pebble#46] opened 2021-05-24 05:45 UTC
I tried setting up the service with a command that ends with output code 1 (due missing python package). However, the service says that it is running without any errors. 

An [example](https://pastebin.ubuntu.com/p/y9r88xNXYR/) of what I mean.

**Comment by benhoyt** [comment] 2021-05-24 07:05
Yes, this is strange, thanks. Can you use `/bin/sh -c "commandline >out.log"` or similar, so we can see the test output and ensure the output is actually the same as what you get when running it manually?

Also, note that `|| exit 2` is a shell feature, whereas Pebble commands are executed directly without the shell. So you'd need to run that first command using `bash -c` or similar if you want that shell-style behavior.

**Comment by r-f-g** [comment] 2021-05-27 10:41
```bash
root@mlflow-0:/mlflow# /charm/bin/pebble plan
services:
    server:
        summary: MLflow server
        startup: enabled
        override: replace
        command: /bin/sh -c "mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri mysql+pymysql://mysql:password@10.152.183.150:3306/database --default-artifact-root s3://mlflow/ > mlflow-server.log 2>&1;echo exit-code $? >> mlflow-server.log 2>&1"
        environment:
            AWS_ACCESS_KEY_ID: minio
            AWS_SECRET_ACCESS_KEY: minio1234
            MLFLOW_S3_ENDPOINT_URL: http://minio:9000
            MLFLOW_S3_IGNORE_TLS: "true"
root@mlflow-0:/mlflow# ls -lha
total 136K
drwxr-xr-x 1 root root 4.0K May 27 10:40 .
drwxr-xr-x 1 root root 4.0K May 27 10:39 ..
-rw-r--r-- 1 root root 2.1K May 27 10:40 mlflow-server.log
-rw-r--r-- 1 root root 116K May 27 10:40 mlflow.db
drwxr-xr-x 2 root root 4.0K May 27 10:40 mlruns
root@mlflow-0:/mlflow# cat mlflow-server.log
2021/05/27 10:40:19 ERROR mlflow.cli: Error initializing backend store
2021/05/27 10:40:19 ERROR mlflow.cli: No module named 'pymysql'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mlflow/cli.py", line 383, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 145, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 130, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 38, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 101, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 102, in __init__
    self.engine = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 159, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 189, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 68, in dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
exit-code 1
```

**Comment by benhoyt** [comment] 2021-05-28 00:17
Hmmm, I can't reproduce this locally with Pebble. If I try to start a service with command `python3 -c "import foo"` to simulate the "No module name 'x'` error that you're getting, the service fails to start and `pebble services` shows it as inactive.

Based on your logs/output, you have a service "server" which is failing, and `pebble start` shows it's failing to start and `pebble services` shows it's inactive. And then there's the service "test", which is succeeding, and `pebble start` succeeds and `pebble services` shows it's active. So I might be missing something, but I'm not quite sure what the problem is here?

**Comment by fnordahl** [comment] 2021-05-28 05:46
I see the same thing.

In my case I'm attempting to start a image-provided shell script which will perform a configure step before starting the final service. If this process fails I do not get any notification and direct polls for whether the service runs returns inaccurate information.

I can reproduce the issue with

layer.yaml:
```yaml
summary: reproducer
description: |
    reproducer for https://github.com/canonical/pebble/issues/46
services:
    srv1:
        summary: srv1
        startup: enabled
        override: replace
        command: /tmp/start.sh
```
start.sh:
```bash
#!/bin/bash

sleep 2
exit 2
```

pebble output:
```
$ _build/_/bin/pebble plan
services:
    srv1:
        summary: srv1
        startup: enabled
        override: replace
        command: /tmp/start.sh

$ _build/_/bin/pebble autostart

$ sleep 3

$ _build/_/bin/pebble services
Service  Startup  Current
srv1     enabled  active

$ _build/_/bin/pebble autostart
error: cannot perform the following tasks:
- Start service "srv1" (service "srv1" was previously started)

$ _build/_/bin/pebble stop srv1

$ _build/_/bin/pebble autostart

$ _build/_/bin/pebble services
Service  Startup  Current
srv1     enabled  active
```

**Comment by r-f-g** [comment] 2021-05-28 07:06
> Hmmm, I can't reproduce this locally with Pebble. If I try to start a service with command `python3 -c "import foo"` to simulate the "No module name 'x'`error that you're getting, the service fails to start and`pebble services` shows it as inactive.
> 
> Based on your logs/output, you have a service "server" which is failing, and `pebble start` shows it's failing to start and `pebble services` shows it's inactive. And then there's the service "test", which is succeeding, and `pebble start` succeeds and `pebble services` shows it's active. So I might be missing something, but I'm not quite sure what the problem is here?

Both the `server` and `test` services are based on the `mlflow run ...` command, which failed to start with exit code 1 ==> Both of these services should be inactive.

I think the problem is that if the command doesn't end too fast, the service is declared as active. Here is a modified version of what you tried.
```bash
$ /charm/bin/pebble plan
services:
    test:
        summary: test
        startup: enabled
        override: replace
        command: python3 -c "import time;time.sleep(0.1);import foo"
$ /charm/bin/pebble start test
error: cannot perform the following tasks:
- Start service "test" (cannot start service: exited quickly with code 1)
$ /charm/bin/pebble plan
services:
    test:
        summary: test
        startup: enabled
        override: replace
        command: python3 -c "import time;time.sleep(0.5);import foo"
$ /charm/bin/pebble start test
error: cannot perform the following tasks:
- Start service "test" (cannot start service: exited quickly with code 1)
$ /charm/bin/pebble plan
services:
    test:
        summary: test
        startup: enabled
        override: replace
        command: python3 -c "import time;time.sleep(1);import foo"
$ /charm/bin/pebble start test
$ /charm/bin/pebble services
Service  Startup  Current
test     enabled  active
```

**Comment by addyess** [comment] 2021-06-24 21:20
In a similar vein to this, I encountered an issue where stopping the service took a very long time, to which pebble finally decided the service was **stopped** when in fact the service was still running.  if I started the service again with pebble, the second service could never start because of the other long-running **stop** process. 

it seems that pebble doesn't really have enough enumeration for the service states like:
_starting_ or _stopping_

Not to mention i could find no uses of the _error_ enumeration being used
https://github.com/canonical/pebble/blob/52c8d6b3e55ab8574806980aa15c1a719876c69b/internal/overlord/servstate/manager.go#L204-L208

**Comment by dstathis** [comment] 2021-09-14 20:17
I have hit this as well

```
dylan@cerritos:~/cassandra-operator$ js
Model  Controller      Cloud/Region    Version  SLA          Timestamp
lma    mk8s-localhost  mk8s/localhost  2.9.14   unsupported  20:14:36Z

App             Version  Status  Scale  Charm           Store     Channel  Rev  OS          Address         Message
cassandra-k8s            active      3  cassandra-k8s   local                0  kubernetes  10.152.183.238  
grafana-k8s              active      1  grafana-k8s     charmhub  edge       9  kubernetes  10.152.183.156  
prometheus-k8s           active      1  prometheus-k8s  charmhub  edge       9  kubernetes  10.152.183.103  

Unit               Workload  Agent  Address       Ports  Message
cassandra-k8s/0*   active    idle   10.1.250.220         
cassandra-k8s/1    active    idle   10.1.250.221         
cassandra-k8s/2    active    idle   10.1.250.222         
grafana-k8s/0*     active    idle   10.1.250.224         
prometheus-k8s/0*  active    idle   10.1.250.223         

dylan@cerritos:~/cassandra-operator$ kubectl exec cassandra-k8s-0 -c cassandra -- ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0 712564  6988 ?        SLsl 19:56   0:00 /charm/bin/pebble run --create-dirs --hold --verbose
root         762  0.0  0.0   8892  3228 ?        Rs   20:14   0:00 ps aux
```

I think what is happening is pebble waits a certain amount of time for the service to exit non zero then reports it as started. At the very least, this amount of time should be configurable. Ideally, though, pebble would check the service continually.

**Comment by benhoyt** [comment] 2021-11-29 00:53
This has been fixed with the new auto-restart and backoff work: https://github.com/canonical/pebble/pull/79

**Closed by benhoyt** 2021-11-29 00:53 UTC
